name: CD Pipeline

on:
  push:
    branches: [master]
    paths:
      - "package.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: |
          yarn install
          yarn run build
          yarn run test
          version=`npm view @3r/tool version`;
          unpublish=`npm deprecate @3r/tool@$verison '这个版本仅开发用来测试'`
          echo $version
          if [[ $version =~ '-' ]] then $unpublish fi
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NpmToken}}
