name: CI Pipeline

on:
  push:
    branches: [master]
    paths:
      - "**/*.js"
      - "**/*.ts"
  pull_request:
    branches: [master]
    paths:
      - "**/*.js"
      - "**/*.ts"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: |
          yarn install
          yarn run lint
          npx tsc
          yarn run test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
