name: Release Pipeline

on:
  push:
    branches: [master]
    paths:
      - "CHANGELOG.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: |
          yarn install
          node build/release.js '${{ secrets.GITHUB_TOKEN }}' 'linyisonger' '3r.Tool' 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Update Github gh-pages
