name: Release Pipeline

on:
  push:
    branches: [master]
    paths:
      - "CHANGELOG.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: |
          yarn install
          node build/release.js '${{ secrets.GITHUBTOKEN }}' 'linyisonger' '3r.Tool'
